In [1]:
import pandas as pd

/opt/conda/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
# read pretrained1 result
df1 = pd.read_csv('tsla_merged_res.csv')
df1.rename(columns={"Unnamed: 0": "Index"}, inplace=True) # DataFrame 的原始內容將被更改
df1

,Index,Date,Content,label,score
0,0,2020-12-31,Tesla short sellers lost billions more on the ...,negative,0.998547
1,1,2020-12-31,Enphase joins Tesla as the latest clean tech f...,neutral,0.999871
2,2,2020-12-29,"In 2021, the breadth of the competitive attack...",positive,0.980603
3,3,2020-12-28,"In 2021, the breadth of the competitive attack...",positive,0.980603
4,4,2020-12-25,Elon Musk says it’s “impossible” to take Tesla...,neutral,0.994511
...,...,...,...,...,...
11144,11144,2015-02-13,Apple has assigned 100s of staffers to an elec...,neutral,0.999865
11145,11145,2015-01-28,"Apple, Microsoft and Tesla shops are helping h...",neutral,0.997585
11146,11146,2015-01-17,Elon Musk says Tesla won't be profitable until...,negative,0.973701
11147,11147,2015-01-14,Elon Musk says Tesla won't be profitable until...,negative,0.971959
11148,11148,2015-01-12,"Elon Musk is pushing hard to sell 500,000 Tesl...",neutral,0.997710

In [5]:
# read pretrained2 result
df2 = pd.read_csv('tsla_merged_res_2.csv')
df2.rename(columns={"Unnamed: 0": "Index"}, inplace=True) # DataFrame 的原始內容將被更改
df2

,Index,Date,Content,label,score
0,0,2020-12-31,Tesla short sellers lost billions more on the ...,negative,0.998842
1,1,2020-12-31,Enphase joins Tesla as the latest clean tech f...,positive,0.943688
2,2,2020-12-29,"In 2021, the breadth of the competitive attack...",positive,0.571425
3,3,2020-12-28,"In 2021, the breadth of the competitive attack...",positive,0.571425
4,4,2020-12-25,Elon Musk says it’s “impossible” to take Tesla...,neutral,0.895259
...,...,...,...,...,...
11144,11144,2015-02-13,Apple has assigned 100s of staffers to an elec...,neutral,0.999158
11145,11145,2015-01-28,"Apple, Microsoft and Tesla shops are helping h...",neutral,0.619423
11146,11146,2015-01-17,Elon Musk says Tesla won't be profitable until...,neutral,0.846004
11147,11147,2015-01-14,Elon Musk says Tesla won't be profitable until...,neutral,0.849185
11148,11148,2015-01-12,"Elon Musk is pushing hard to sell 500,000 Tesl...",neutral,0.986418

In [7]:
# 設定空的列表來儲存比較結果
comparison_data = []

# t=0
# 迴圈逐行比較兩個DataFrame
for index, row in df1.iterrows():
    # if t>10:
    #     break
    date = row['Date']
    content = row['Content']
    label_file1 = row['label']
    score_file1 = row['score']
    
    # 找到與df1相同index的資料
    df2_row = df2[df2['Index'] == index]
    
    if not df2_row.empty:
        label_file2 = df2_row['label'].iloc[0]
        score_file2 = df2_row['score'].iloc[0]
        
        if label_file1 == label_file2: # label 相同
            scorefinal = 0.5 * (score_file1 + score_file2)
            # print(score1, score2, scorefinal)
            
            # 將比較結果新增至comparison_data
            comparison_data.append({'Date': date,
                                    'Content': content,
                                    'label': label_file1,
                                    'final_score': scorefinal})
        # t+=1
    else:
        continue

# 將比較結果轉換為DataFrame
comparison_df = pd.DataFrame(comparison_data)

# 印出比較結果
print(comparison_df)

            Date                                            Content     label  \
0     2020-12-31  Tesla short sellers lost billions more on the ...  negative
1     2020-12-29  In 2021, the breadth of the competitive attack...  positive
2     2020-12-28  In 2021, the breadth of the competitive attack...  positive
3     2020-12-25  Elon Musk says it’s “impossible” to take Tesla...   neutral
4     2020-12-25  Elon Musk has made millionaires out of Tesla's...   neutral
...          ...                                                ...       ...
8960  2015-02-16  Apple has assigned hundreds of staffers to an ...   neutral
8961  2015-02-16  Apple gears up to challenge Tesla in electric ...   neutral
8962  2015-02-13  Apple has assigned 100s of staffers to an elec...   neutral
8963  2015-01-28  Apple, Microsoft and Tesla shops are helping h...   neutral
8964  2015-01-12  Elon Musk is pushing hard to sell 500,000 Tesl...   neutral

      final_score
0        0.998694
1        0.776014
2        0.776014
3        0.944885
4        0.766958
...           ...
8960     0.994201
8961     0.996125
8962     0.999512
8963     0.808504
8964     0.992064

[8965 rows x 4 columns]

In [8]:
comparison_df.to_csv('tsla_dataset.csv', index=False)