In [2]:
import pandas as pd

In [27]:
df1 = pd.read_csv('twitter.csv')
df1.rename(columns = {"Unnamed: 0": "Index"}, inplace = True)
df1

,Index,summary,label,score
0,0,"Elon Musk, J.B. Straubel, Deepak Ahuja and Dou...",neutral,0.547312
1,1,The vast majority of the Tesla production syst...,negative,0.582673
2,2,We've added cost. We'veadded a manufacturing s...,neutral,0.566878
3,3,"In the third quarter, it will -- I think there...",positive,0.878674
4,4,"Elon R. Musk: I think a 5-day, 2-shift operati...",neutral,0.568415
...,...,...,...,...
344,344,Your next question comes from Pierre Ferragu w...,neutral,0.870525
345,345,"Zachary Kirkhorn - Tesla, Inc. - CFOYes. I mea...",positive,0.870579
346,346,"Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...",neutral,0.796123
347,347,"Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...",positive,0.657266
348,348,"Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...",positive,0.760418

In [28]:
df2 = pd.read_csv('distilbert.csv')
df2.rename(columns = {"Unnamed: 0": "Index"}, inplace = True)
df2

,Index,summary,label,score
0,0,"Elon Musk, J.B. Straubel, Deepak Ahuja and Dou...",positive,0.765201
1,1,The vast majority of the Tesla production syst...,negative,0.765059
2,2,We've added cost. We'veadded a manufacturing s...,positive,0.635821
3,3,"In the third quarter, it will -- I think there...",positive,0.697074
4,4,"Elon R. Musk: I think a 5-day, 2-shift operati...",negative,0.698246
...,...,...,...,...
344,344,Your next question comes from Pierre Ferragu w...,neutral,0.773718
345,345,"Zachary Kirkhorn - Tesla, Inc. - CFOYes. I mea...",positive,0.809214
346,346,"Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...",neutral,0.705739
347,347,"Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...",neutral,0.459538
348,348,"Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...",positive,0.687168

In [29]:
comparison_data = []
for index, row in df1.iterrows():
    
    #刪掉空的column
    summary = row['summary']
    label_file1 = row['label']
    score_file1 = row['score']
    
    #自己新增Index
    df2_row = df2[df2['Index'] == index]
    
    if not df2_row.empty:
        label_file2 = df2_row['label'].iloc[0]
        score_file2 = df2_row['score'].iloc[0]
        
        if label_file1 == label_file2:
            scorefinal = 0.5 * (score_file1 + score_file2)
  
            comparison_data.append({
                                    'summary': summary,
                                    'label': label_file1,
                                    'final_score': scorefinal})
    else:
        continue
comparison_df = pd.DataFrame(comparison_data)

print(comparison_df)

                                               summary     label  final_score
0    The vast majority of the Tesla production syst...  negative     0.673866
1    In the third quarter, it will -- I think there...  positive     0.787874
2    The takt -- the number you're referring to is ...   neutral     0.773035
3    Deepak Ahuja: Every data point suggests that w...   neutral     0.554324
4    Elon R. Musk: I feel very confident about our ...  positive     0.685584
..                                                 ...       ...          ...
257  When people had CRT TVs, there's no cathode ra...   neutral     0.543128
258  Your next question comes from Pierre Ferragu w...   neutral     0.822122
259  Zachary Kirkhorn - Tesla, Inc. - CFOYes. I mea...  positive     0.839897
260  Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...   neutral     0.750931
261  Elon R. Musk - Tesla, Inc. - Founder, CEO & Di...  positive     0.723793

[262 rows x 3 columns]

In [31]:
comparison_df.to_csv('earningscall_final.csv', index = False)